name: "Social media integrations"

on:
  push:
    branches: "master"
jobs:
  CreateImage:
    name: Create repo img for social media
    runs-on: ubuntu-latest
    steps:
      - name: Open Graph social cards
        uses: rodcordeiro/open-graph-image@v1.2
        with:
          bold-text: "RChat"
          plain-text: "A Live chat with ReactJS, Typescript and Socket.IO"
          theme: "dark"

      - name: Archive open graph image
        uses: actions/upload-artifact@v2
        with:
          name: open-graph-image
          path: og-image.now.sh.png

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
  Resk:
    name: Create code gists for example
    runs-on: ubuntu-latest
    steps:
      - name: Run resk tool
        run: npx resk rodcordeiro/rchat
        env:
          GH_TOKEN: ${{ secrets.GIST }}
